### ISSUE TITLE
build error on new clone

### ISSUE THREAD

**Issue by rtennill** [rlk/scm#3]
need to include stdio.h or use cout instead.

    g++ -O2 -DNDEBUG -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/freetype2 -c scm-set.cpp -o scm-set.o
    scm-set.cpp: In member function ‘void scm_set::dump() const’:
    scm-set.cpp:109:30: error: ‘printf’ was not declared in this scope
        printf("%lu : ", m.size());
                                 ^
    make: *** [scm-set.o] Error 1

**Comment by rlk** [comment]
Resolved with the inclusion of <cstdio>.
